// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmsijzupxhzifjhnmlcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtc2lqenVweGh6aWZqaG5tbGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzA5ODgsImV4cCI6MjA2MzMwNjk4OH0.-6mSQTovCgd13sOFOOb6rVXvpCf4xWn--rryLO5gktM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);